# Generated by Django 5.0 on 2024-03-04 15:42

import django.db.models.deletion
import django.utils.timezone
import product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=product.models.user_directory_path)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='draft', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=product.models.user_directory_path)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='draft', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='draft', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('link', models.CharField(max_length=250, null=True)),
                ('thumbnail', models.ImageField(upload_to=product.models.user_directory_path)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('sku', models.CharField(max_length=500, null=True, unique=True)),
                ('thumbnail', models.ImageField(upload_to=product.models.user_directory_path)),
                ('image1', models.ImageField(upload_to=product.models.user_directory_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=product.models.user_directory_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=product.models.user_directory_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=product.models.user_directory_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=product.models.user_directory_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=product.models.user_directory_path)),
                ('sale', models.BooleanField(default=False)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bestoffer', models.BooleanField(default=False)),
                ('on_stock', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='draft', max_length=10)),
                ('featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_posts', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(default=1, max_length=250, on_delete=django.db.models.deletion.PROTECT, to='product.brand')),
                ('category', models.ForeignKey(default=1, max_length=250, on_delete=django.db.models.deletion.PROTECT, to='product.category')),
                ('compare', models.ManyToManyField(blank=True, default=None, related_name='compare', to=settings.AUTH_USER_MODEL)),
                ('quality', models.ForeignKey(default=1, max_length=250, on_delete=django.db.models.deletion.PROTECT, to='product.quality')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_description', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=product.models.user_directory_path)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='draft', max_length=10)),
                ('category', models.ForeignKey(default=1, max_length=250, on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.subcategory'),
        ),
    ]
